# Generated by Django 5.2 on 2025-04-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('nota_actividad', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_educativo',
            fields=[
                ('id_nivel_educativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_estudio',
            fields=[
                ('id_plan_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan_estudio', models.CharField(max_length=100)),
                ('link_plan_estudio', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_leccion',
            fields=[
                ('id_plan_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan_leccion', models.CharField(max_length=80)),
                ('link_plan_leccion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('actividades', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.actividades')),
                ('aulas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.aulas')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('estado_asistencia', models.BooleanField(default=False)),
                ('aulas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.aulas')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.materia')),
            ],
        ),
        migrations.AddField(
            model_name='aulas',
            name='nivel_eductativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo'),
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tema', models.CharField(max_length=100)),
                ('periodo_academico', models.CharField(max_length=20)),
                ('plan_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.plan_leccion')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='temas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.temas'),
        ),
        migrations.CreateModel(
            name='Usuarios_registrados',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=20)),
                ('numero_doc', models.CharField(max_length=20)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('estado_usuario', models.BooleanField(default=False)),
                ('contraseña', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('foto_usuario', models.CharField(blank=True, max_length=240, null=True)),
                ('nivel_eductativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.roles')),
            ],
        ),
        migrations.AddField(
            model_name='aulas',
            name='usuarios_registrados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuarios_registrados'),
        ),
    ]
