# Generated by Django 5.2 on 2025-05-23 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('descripcion_actividad', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_educativo',
            fields=[
                ('id_nivel_educativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_estudio',
            fields=[
                ('id_plan_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan_estudio', models.CharField(max_length=100)),
                ('link_plan_estudio', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_leccion',
            fields=[
                ('id_plan_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan_leccion', models.CharField(max_length=80)),
                ('link_plan_leccion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador')], default='DOCENTE', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('actividades', models.ManyToManyField(blank=True, to='tasks.actividades')),
                ('aulas', models.ManyToManyField(blank=True, to='tasks.aulas')),
                ('plan_estudio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.plan_estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('estado_asistencia', models.BooleanField(default=False)),
                ('aulas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.aulas')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.materia')),
            ],
        ),
        migrations.AddField(
            model_name='aulas',
            name='nivel_educativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo'),
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tema', models.CharField(max_length=100)),
                ('periodo_academico', models.CharField(max_length=20)),
                ('plan_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.plan_leccion')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='temas',
            field=models.ManyToManyField(blank=True, to='tasks.temas'),
        ),
        migrations.CreateModel(
            name='Usuarios_registrados',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3)),
                ('numero_doc', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('estado_usuario', models.BooleanField(choices=[(True, 'activo'), (False, 'inactivo')], default=False)),
                ('contraseña', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('foto_usuario', models.CharField(blank=True, max_length=240, null=True)),
                ('nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('actividades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.actividades')),
                ('estudiantes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuarios_registrados')),
            ],
        ),
        migrations.AddField(
            model_name='aulas',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__rol': 'DOCENTE'}, related_name='docente', to='tasks.usuarios_registrados'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__rol': 'ESTUDIANTE'}, related_name='estudiante', to='tasks.usuarios_registrados'),
        ),
    ]
