# Generated by Django 5.2 on 2025-04-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='usuarios_registrados',
        ),
        migrations.AddField(
            model_name='aulas',
            name='usuarios_registrados',
            field=models.ManyToManyField(to='tasks.usuarios_registrados'),
        ),
    ]
