# Generated by Django 5.2 on 2025-06-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_educativo',
            name='nombre_nivel',
            field=models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='roles',
            name='rol',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador')], default='DOCENTE', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3)),
                ('numero_doc', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('estado_usuario', models.BooleanField(choices=[(True, 'activo'), (False, 'inactivo')], default=False)),
                ('contraseña', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('foto_usuario', models.CharField(blank=True, max_length=240, null=True)),
                ('id_coordinador', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3)),
                ('numero_doc', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('estado_usuario', models.BooleanField(choices=[(True, 'activo'), (False, 'inactivo')], default=False)),
                ('contraseña', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('foto_usuario', models.CharField(blank=True, max_length=240, null=True)),
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
                ('Nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aulas',
            name='docentes',
            field=models.ManyToManyField(blank=True, to='tasks.docente'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('tipo_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3)),
                ('numero_doc', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('estado_usuario', models.BooleanField(choices=[(True, 'activo'), (False, 'inactivo')], default=False)),
                ('contraseña', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('foto_usuario', models.CharField(blank=True, max_length=240, null=True)),
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=20)),
                ('Nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='aulas',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='tasks.estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.estudiante'),
        ),
        migrations.DeleteModel(
            name='Usuarios_registrados',
        ),
    ]
