# Generated by Django 5.2 on 2025-06-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_nivel_educativo_nombre_nivel_alter_roles_rol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinador',
            old_name='Nivel_educativo',
            new_name='nivel_educativo',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='Nivel_educativo',
            new_name='nivel_educativo',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='Nivel_educativo',
            new_name='nivel_educativo',
        ),
    ]
