# Generated by Django 5.2 on 2025-04-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_aulas_usuarios_registrados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_educativo',
            name='nombre_nivel',
            field=models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], default='PRIMARIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='roles',
            name='rol',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador')], default='DOCENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios_registrados',
            name='tipo_doc',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3),
        ),
    ]
