# Generated by Django 5.2 on 2025-06-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_nivel_educativo_coordinador_nivel_educativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='rol',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador')], default='DOCENTE', max_length=20, null=True, unique=True),
        ),
    ]
