# Generated by Django 5.2 on 2025-04-21 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_nivel_educativo_nombre_nivel_alter_roles_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='usuarios_registrados',
        ),
        migrations.AddField(
            model_name='aulas',
            name='docentes',
            field=models.ManyToManyField(limit_choices_to={'roles__rol': 'DOCENTE'}, related_name='docentes', to='tasks.usuarios_registrados'),
        ),
        migrations.AddField(
            model_name='usuarios_registrados',
            name='aulas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.aulas'),
        ),
    ]
