# Generated by Django 5.2 on 2025-06-04 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_roles_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.roles'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.roles'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.roles'),
        ),
    ]
