# Generated by Django 5.2 on 2025-04-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_aulas_usuarios_registrados_aulas_docentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_registrados',
            name='estado_usuario',
            field=models.BooleanField(choices=[(True, 'activo'), (False, 'inactivo')], default=False),
        ),
    ]
