# Generated by Django 5.2 on 2025-06-04 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_coordinador_roles_alter_docente_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.materia'),
        ),
    ]
