# Generated by Django 5.2 on 2025-04-22 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_usuarios_registrados_estado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='estudiantes',
            field=models.ManyToManyField(limit_choices_to={'roles__rol': 'ESTUDIANTE'}, null=True, related_name='estudiante', to='tasks.usuarios_registrados'),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='docentes',
            field=models.ManyToManyField(limit_choices_to={'roles__rol': 'DOCENTE'}, null=True, related_name='docentes', to='tasks.usuarios_registrados'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='rol',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador')], default='DOCENTE', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios_registrados',
            name='aulas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.aulas'),
        ),
    ]
