# Generated by Django 5.2 on 2025-06-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_docente_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='materia',
            name='docentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.docente'),
        ),
    ]
