# Generated by Django 5.2 on 2025-04-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_aulas_estudiantes_alter_aulas_docentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='aulas',
            name='estudiantes',
            field=models.ForeignKey(limit_choices_to={'roles__rol': 'ESTUDIANTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante', to='tasks.usuarios_registrados'),
        ),
    ]
