# Generated by Django 5.2 on 2025-06-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_docente_asignatura_materia_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='docentes_asignados', to='tasks.materia'),
        ),
    ]
