# Generated by Django 5.2 on 2025-04-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_aulas_estudiantes_aulas_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='aulas',
            name='estudiantes',
            field=models.ManyToManyField(limit_choices_to={'roles__rol': 'ESTUDIANTE'}, null=True, related_name='estudiante', to='tasks.usuarios_registrados'),
        ),
    ]
