# Generated by Django 5.2 on 2025-04-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_aulas_estudiantes_aulas_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_registrados',
            name='aulas',
        ),
    ]
