# Generated by Django 5.2 on 2025-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_usuarios_registrados_aulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='docentes',
            field=models.ManyToManyField(limit_choices_to={'roles__rol': 'DOCENTE'}, null=True, related_name='docente', to='tasks.usuarios_registrados'),
        ),
    ]
