# Generated by Django 5.2 on 2025-04-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_aulas_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='aulas',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='temas',
        ),
        migrations.AddField(
            model_name='materia',
            name='actividades',
            field=models.ManyToManyField(blank=True, to='tasks.actividades'),
        ),
        migrations.AddField(
            model_name='materia',
            name='aulas',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.aulas'),
        ),
        migrations.AddField(
            model_name='materia',
            name='temas',
            field=models.ManyToManyField(blank=True, to='tasks.temas'),
        ),
    ]
