# Generated by Django 5.2 on 2025-04-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_materia_actividades_remove_materia_aulas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='plan_estudio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.plan_estudio'),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='docentes',
            field=models.ManyToManyField(limit_choices_to={'roles__rol': 'DOCENTE'}, related_name='docente', to='tasks.usuarios_registrados'),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='estudiantes',
            field=models.ManyToManyField(limit_choices_to={'roles__rol': 'ESTUDIANTE'}, related_name='estudiante', to='tasks.usuarios_registrados'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='aulas',
            field=models.ManyToManyField(blank=True, to='tasks.aulas'),
        ),
    ]
