# Generated by Django 5.2 on 2025-04-24 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_materia_plan_estudio_alter_aulas_docentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_registrados',
            name='nivel_eductativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.nivel_educativo'),
        ),
    ]
