# Generated by Django 5.2 on 2025-04-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_usuarios_registrados_nivel_eductativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__rol': 'DOCENTE'}, related_name='docente', to='tasks.usuarios_registrados'),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__rol': 'ESTUDIANTE'}, related_name='estudiante', to='tasks.usuarios_registrados'),
        ),
    ]
