# Generated by Django 5.2 on 2025-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='nota_actividad',
        ),
        migrations.AddField(
            model_name='actividades',
            name='descripcion_actividad',
            field=models.TextField(blank=True),
        ),
    ]
