# Generated by Django 5.2 on 2025-04-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_actividades_nota_actividad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios_registrados',
            old_name='nivel_eductativo',
            new_name='nivel_educativo',
        ),
    ]
